### ISSUE TITLE
esptool: error: argument operation: invalid choice: '{upload.flags}'

### ISSUE THREAD

**Issue by SteffenLav** [dl1bz/ESP32-IC705BT-PA#1]
When compiling the CIV_template.ino I get the following esptool error:
`argument operation: invalid choice: '{upload.flags}' (choose from 'load_ram', 'dump_mem', 'read_mem', 'write_mem', 'write_flash', 'run', 'image_info', 'make_image', 'elf2image', 'read_mac', 'chip_id', 'flash_id', 'read_flash_status', 'write_flash_status', 'read_flash', 'verify_flash', 'erase_flash', 'erase_region', 'merge_bin', 'get_security_info', 'version')
`
Probably something I did wrong or?

Thanks,
Steffen de OZ1LAV

**Comment by dl1bz** [comment]
No, you didn't.
Look here for solution: [https://forum.arduino.cc/t/how-to-display-image-on-ttgo-t-display-esp32/1174923](url)

73 Heiko, DL1BZ

**Comment by SteffenLav** [comment]
That was it - now working!
Thanks Heiko

73 Steffen de OZ1LAV

**Comment by dl1bz** [comment]
Maybe an issue in the ESP32-SDK from Espressif. The other option is simply using an ESP32-Dev board as selection. That was working here without patching the boards.txt. 

Also attention with the Lib TFT_eSPI. I was using only this here: [https://github.com/Xinyuan-LilyGO/TTGO-T-Display/tree/master/TFT_eSPI](https://github.com/Xinyuan-LilyGO/TTGO-T-Display/tree/master/TFT_eSPI). With the other, newer Lib I had some problems with the T-DISPLAY. Beware, the Arduino IDE will make an update of this older lib, so don't do it ! Thats only important if you use only the LILYGO T-DISPLAY v1.1.
Next, with the newer S3-versions of ESP32 you lost classical Blutooth, start from S3 there are only Bluetooth LE possible and will NOT work with my code. You need BT-profile SPP, BT-LE hasn't ! BT classical and BT LE are two complete different things. LE is client-server based and need a complete new codebase for BT with the 705. But in the meantime I changed from 705 to Hermes-Lite 2 and so *this* project is no more needed by me. My XPA125B is now my PA for the Hermes-Lite 2. I develop another project with an ESP32 (in this case with an ESP32-S3) too for using the XPA125B with the Hermes-Lite 2. The using of TFT display was only a gimmick, but for practical use it's not needed. 

73 Heiko, DL1BZ
