### ISSUE TITLE
Scam link in description 

### ISSUE THREAD

**Issue by omnislash772** [dl1bz/ESP32-IC705BT-PA#2]
Carnut.info seems to have turned into a viagra drugs scam
Consider changing this link to the way back machine version.
https://web.archive.org/web/20230128134910/http://www.carnut.info/IC-705/ICOM_IC-705.html#BT

**Comment by dl1bz** [comment]
If I go to this page/link, it looks normal like earlier. I see no reason to change this link.

73 Heiko, DL1BZ
